### PR TITLE
Reuse all arguments

### PR DESCRIPTION
**Pull request by 927589452**
this is based on #10 so, best apply that one first

more explanation on the change can be found here
https://stackoverflow.com/questions/4824590/propagate-all-arguments-in-a-bash-shell-script

### CODE REVIEW

**Comment by 927589452** [comment]
correction as it includes the changes it should fast forward hopefully

**Comment by GideonWolfe** [comment]
@927589452 Not sure if it's because of this merge, but now running `zathura filename` leaves the terminal hanging. I had it previously where it would detach zathura so you could keep using the terminal.

**Comment by 927589452** [comment]
mine does detach; 
(the trailing `&` does the forking)
though a better solution might be to add `--fork` to the script

**Comment by GideonWolfe** [comment]
@927589452 Is there a chance you could take a look at this again?

I revisited this after a bit and stuff ain't working right. Cloned the directory fresh and did a fresh install.

1. Even after adding `$HOME/.local/bin` to my `$PATH`, `usr/bin/zathura` is still used by default.
2. I removed the `smooth-scroll` option because it randomly started throwing an "unknown option" error. Updated the files but the error persists.
3. Now I see the error `warning: undefined link destination` when I open a file.

Man I had this working fine when it was simple and now I can't seem to get it working at all, and it's my own script...

I think the main issue is the default path. On my Main PC it works fine, and `which zathura` returns the correct path `/home/gideon/.local/bin` but on my laptop it returns `/usr/bin/`.

**Comment by 927589452** [comment]
> I think the main issue is the default path. On my Main PC it works fine, and `which zathura` returns the correct path `/home/gideon/.local/bin` but on my laptop it returns `/usr/bin/`.

Did you change the $PATH in your .bashrc on your notebook too?

**Comment by GideonWolfe** [comment]
Sigh... The filepath was in `$PATH`, just not in the correct order. Took me a bit to get it with `fish` but it works great now

**Pull request merged**
